#ifndef SD_BATCH_H
#define SD_BATCH_H

/*
 * SD card batch evaluation.
 *
 * Expects the SD card to contain:
 *   /BIRDSPEC/labels.csv   — CSV: "filename,class_idx\n" for each sample
 *   /BIRDSPEC/XXXX.bin     — raw int8_t[8192] spectrogram tensor per sample
 *
 * Generated by tools/gen_test_tensors.py.
 *
 * Prints a JSONL summary line per sample and a final statistics object
 * over UART when done.
 */

/*
 * Initialise the SDHC peripheral and mount FatFS.
 * Call once at boot (before sd_batch_run).
 */
void sd_batch_init(void);

/*
 * Run batch inference.
 *   max_samples: maximum number of samples to evaluate (0 = all).
 * Results are printed over UART as JSON lines:
 *   {"idx":0,"file":"0000.bin","truth":47,"pred":47,"conf":91.2,"lat_us":41823}
 * Followed by a summary:
 *   {"batch_done":true,"n":1864,"correct":1329,"accuracy":71.3,"lat_mean_us":42000}
 */
void sd_batch_run(int max_samples);

#endif /* SD_BATCH_H */
